version: '3'
services:
  personal-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:80"
    restart: unless-stopped
    container_name: personal-website-container
